export const GET_USERS = 'GET_USERS'
export const USERS_ERROR = 'USERS_ERROR'
export const GET_DATA = 'GET_DATA'
export const SET_CURRENT_DISP = 'SET_CURRENT_DISP'
export const SET_LOADING = 'SET_LOADING'
export const SET_FULLY_LOADED = 'SET_FULLY_LOADED'
export const SET_LOOKUP = 'SET_LOOKUP'
export const DATA_ERROR = 'DATA_ERROR'
